version: '3.1'
services:
  app:
    image: node:16-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
      - 80:8000
    working_dir: /app
    volumes:
      - './app/src:/app/src'
      - './app/package.json:/app/package.json'
      - './app/yarn.lock:/app/yarn.lock'
